// ==================== DATA LAYER ====================
export const CATAMARAN_DATA = {
  destiny: {
    id: 'destiny',
    name: 'Destiny',
    category: 'party',
    description: 'High-energy party cruise experience',
    mood: 'Energetic & Fun',
    vibe: 'Party all day on crystal waters',
    heroImage:
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802334/4_vg6qwh.jpg',
    videoUrl:
      'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4',
    image:
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802334/4_vg6qwh.jpg',
    gallery: [
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802334/1_wvnp2r.jpg',
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802335/3_oahsqo.jpg',
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802334/4_vg6qwh.jpg',
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802334/2_vrbyj2.jpg',
    ],
    pricing: {
      minimumRate: 350,
      baseGroupSize: 5,
      additionalPersonRate: 25,
      currency: 'USD',
    },
    timeSlots: [
      { id: 'morning', time: '8:30 AM - 11:30 AM' },
      { id: 'midday', time: '11:30 AM - 2:30 PM' },
      { id: 'afternoon', time: '2:30 PM - 5:30 PM' },
    ],
    duration: '3 hours',
    capacity: 50,
    premium: false,
    price: 89,
    features: [
      'DJ & Sound System',
      'Dance Floor',
      'Party Games',
      'Premium Open Bar',
      'Party Snacks',
      'Water Sports',
    ],
    highlights: ['DJ music', 'Dance party', 'Water activities'],
    includes: [
      'Catamarán y gasolina',
      'Transporte privado de ida y vuelta desde su hotel o villa',
      'Open Bar Cócteles variados: vodka cranberry, gin tonic, Ron punch, Cuba libre, mojito y piña colada (elegir 4 tipos)',
      'Hielo, agua, refrescos',
      'Frutas tropicales',
      'Nachos con salsa',
      'Equipos de esnorquel',
    ],
    destinations: [
      'Piscinas Naturales (bancos de arena)',
      'Zona de esnorquel',
      'Visita el delfinario para ver a los delfines desde el exterior',
    ],
    notes: 'El cliente puede llevar su propia bebida y comida si lo desea.',
    primaryColor: 'from-purple-600 to-pink-600',
    accentColor: 'purple-500',
  },
  liberty: {
    id: 'liberty',
    name: 'Liberty',
    category: 'classic',
    description: 'Perfect introduction to Caribbean sailing',
    mood: 'Classic & Adventurous',
    vibe: 'Discover paradise with authentic Caribbean vibes',
    heroImage:
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802312/2_je7e48.jpg',
    image:
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802312/2_je7e48.jpg',
    gallery: [
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802312/1_sqzbhj.jpg',
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802312/4_v3oped.jpg',
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802312/2_je7e48.jpg',
    ],
    pricing: {
      minimumRate: 400,
      baseGroupSize: 5,
      additionalPersonRate: 25,
      currency: 'USD',
    },
    timeSlots: [
      { id: 'morning', time: '8:30 AM - 11:30 AM' },
      { id: 'midday', time: '11:30 AM - 2:30 PM' },
      { id: 'afternoon', time: '2:30 PM - 5:30 PM' },
    ],
    duration: '3 hours',
    capacity: 40,
    premium: false,
    price: 89,
    features: [
      'Open Bar',
      'Buffet Lunch',
      'Snorkeling Equipment',
      'Professional Crew',
      'Music System',
    ],
    highlights: ['Beach stops', 'Snorkeling', 'Local cuisine'],
    includes: [
      'Catamarán y gasolina',
      'Transporte privado de ida y vuelta desde su hotel o villa',
      'Open Bar Cócteles variados: vodka cranberry, gin tonic, Ron punch, Cuba libre, mojito y piña colada (elegir 4 tipos)',
      'Hielo, agua, refrescos',
      'Frutas tropicales',
      'Nachos con salsa',
      'Equipos de esnorquel',
    ],
    destinations: [
      'Piscinas Naturales (bancos de arena)',
      'Zona de esnorkel',
      'Visita el delfinario para ver a los delfines desde el exterior',
    ],
    notes: 'El cliente puede llevar su propia bebida y comida si lo desea.',
    primaryColor: 'from-blue-600 to-cyan-600',
    accentColor: 'blue-500',
  },
  '45': {
    id: '45',
    name: '45',
    category: 'sunset',
    description: 'Romantic evening cruise for couples',
    mood: 'Romantic & Intimate',
    vibe: 'Fall in love with Caribbean sunsets',
    heroImage:
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802373/6_r2h1ei.jpg',
    image:
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802373/6_r2h1ei.jpg',
    gallery: [
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802373/5_srdzk8.jpg',
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802372/4_onfvkv.jpg',
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802371/3_wwn9g3.jpg',
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802371/2_d9a9ye.jpg',
    ],
    pricing: {
      minimumRate: 400,
      baseGroupSize: 5,
      additionalPersonRate: 25,
      currency: 'USD',
    },
    timeSlots: [
      { id: 'morning', time: '8:30 AM - 11:30 AM' },
      { id: 'midday', time: '11:30 AM - 2:30 PM' },
      { id: 'afternoon', time: '2:30 PM - 5:30 PM' },
    ],
    duration: '3 hours',
    capacity: 20,
    premium: true,
    price: 159,
    features: [
      'Champagne Service',
      'Romantic Dinner',
      'Live Music',
      'Sunset Views',
      'Couples Massage',
      'Photography',
    ],
    highlights: ['Romantic ambiance', 'Sunset views', 'Couples experience'],
    includes: [
      'Catamarán y gasolina',
      'Transporte privado de ida y vuelta desde su hotel o villa',
      'Open Bar Cócteles variados: vodka cranberry, gin tonic, Ron punch, Cuba libre, mojito y piña colada (elegir 4 tipos)',
      'Hielo, agua, refrescos',
      'Frutas tropicales',
      'Nachos con salsa',
      'Equipos de esnorkel',
    ],
    destinations: [
      'Piscinas Naturales (bancos de arena)',
      'Zona de esnorkel',
      'Visita el delfinario para ver a los delfines desde el exterior',
    ],
    notes: 'El cliente puede llevar su propia bebida y comida si lo desea.',
    primaryColor: 'from-orange-600 to-red-600',
    accentColor: 'orange-500',
  },
  trinity: {
    id: 'trinity',
    name: 'Trinity',
    category: 'premium',
    description: 'Luxury sailing with premium amenities',
    mood: 'Luxury & Exclusive',
    vibe: 'Experience the ultimate Caribbean luxury',
    heroImage:
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802359/7_vmobhk.jpg',
    image:
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802359/7_vmobhk.jpg',
    gallery: [
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802356/3_syxzqo.jpg',
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802356/1_wshnpg.jpg',
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802357/2_axcixv.jpg',
      'https://res.cloudinary.com/ddg92xar5/image/upload/v1756802358/5_jmqruo.jpg',
    ],
    pricing: {
      minimumRate: 600,
      baseGroupSize: 15,
      additionalPersonRate: 35,
      currency: 'USD',
    },
    timeSlots: [
      { id: 'morning', time: '8:30 AM - 11:30 AM' },
      { id: 'midday', time: '11:30 AM - 2:30 PM' },
      { id: 'afternoon', time: '2:30 PM - 5:30 PM' },
    ],
    duration: '3 hours',
    capacity: 30,
    premium: true,
    price: 129,
    features: [
      'Premium Bar',
      'Gourmet Buffet',
      'Water Slide',
      'VIP Service',
      'Photo Package',
      'Floating Mats',
    ],
    highlights: ['Water slide', 'Premium drinks', 'VIP treatment'],
    includes: [
      'Catamarán y gasolina',
      'Transporte privado de ida y vuelta desde su hotel o villa',
      'Open Bar Cócteles variados: vodka cranberry, gin tonic, Ron punch, Cuba libre, mojito y piña colada (elegir 4 tipos)',
      'Hielo, agua, refrescos',
      'Frutas tropicales',
      'Nachos con salsa',
      'Equipos de esnorkel',
    ],
    destinations: [
      'Piscinas Naturales (bancos de arena)',
      'Zona de esnorkel',
      'Visita el delfinario para ver a los delfines desde el exterior',
    ],
    notes: 'El cliente puede llevar su propia bebida y comida si lo desea.',
    primaryColor: 'from-amber-600 to-yellow-600',
    accentColor: 'amber-500',
  },
};

export const reviews = [
  {
    name: 'Maria González',
    rating: 5,
    text: 'The premium catamaran was incredible! The water slide and gourmet food made it unforgettable.',
    date: '2 days ago',
    experience: 'Premium Experience',
  },
  {
    name: 'James Wilson',
    rating: 5,
    text: 'Perfect sunset cruise for our anniversary. The romantic dinner and live music were magical.',
    date: '1 week ago',
    experience: 'Sunset Romance',
  },
  {
    name: 'Sophie Martin',
    rating: 5,
    text: 'The party catamaran was amazing! Great DJ, dancing, and the best open bar in Punta Cana.',
    date: '2 weeks ago',
    experience: 'Party Catamaran',
  },
];

export const features = [
  {
    name: 'Open Bar',
    liberty: true,
    trinity: true,
    '45': true,
    destiny: true,
  },
  {
    name: 'Food Service',
    liberty: 'Buffet',
    trinity: 'Gourmet',
    '45': 'Dinner',
    destiny: 'Snacks',
  },
  {
    name: 'Water Slide',
    liberty: false,
    trinity: true,
    '45': false,
    destiny: true,
  },
  {
    name: 'Live Music',
    liberty: false,
    trinity: false,
    '45': true,
    destiny: 'DJ',
  },
  {
    name: 'Dance Floor',
    liberty: false,
    trinity: false,
    '45': false,
    destiny: true,
  },
  {
    name: 'Photography',
    liberty: false,
    trinity: true,
    '45': true,
    destiny: false,
  },
];
